apiVersion: v1
items:
- apiVersion: neuvector.com/v1
  kind: NvSecurityRule
  metadata:
    name: nv.hello-world.default
    namespace: default
  spec:
    dlp:
      settings: []
      status: true
    egress:
    - action: allow
      applications:
      - HTTP
      name: external-egress-0
      ports: any
      priority: 0
      selector:
        comment: ""
        criteria: []
        name: external
        original_name: ""
    - action: allow
      applications:
      - DNS
      name: nv.rke2-coredns-rke2-coredns.kube-system-egress-1
      ports: any
      priority: 0
      selector:
        comment: ""
        criteria:
        - key: service
          op: =
          value: rke2-coredns-rke2-coredns.kube-system
        - key: domain
          op: =
          value: kube-system
        name: nv.rke2-coredns-rke2-coredns.kube-system
        original_name: ""
    file: []
    ingress:
    - action: allow
      applications:
      - HTTP
      name: nv.hello-world.default-ingress-0
      ports: any
      priority: 0
      selector:
        comment: ""
        criteria: []
        name: nodes
        original_name: ""
    - action: allow
      applications:
      - HTTP
      name: nv.hello-world.default-ingress-1
      ports: any
      priority: 0
      selector:
        comment: ""
        name: Workload:ingress
        original_name: ""
    - action: allow
      applications:
      - any
      name: nv.hello-world.default-ingress-2
      ports: tcp/8080
      priority: 0
      selector:
        comment: ""
        name: Workload:ingress
        original_name: ""
    process:
    - action: allow
      allow_update: false
      name: docker-demo
      path: /bin/docker-demo
    - action: allow
      allow_update: false
      name: pause
      path: /pause
    - action: allow
      allow_update: false
      name: sh
      path: /bin/busybox
    process_profile:
      baseline: basic
    target:
      policymode: Protect
      selector:
        comment: ""
        criteria:
        - key: service
          op: =
          value: hello-world.default
        - key: domain
          op: =
          value: default
        name: nv.hello-world.default
        original_name: ""
    waf:
      settings: []
      status: true
kind: List
metadata: null
